todo/urls.py
from django.urls import path
from .views import (
    HomePage,
    LandingPage,
    CrateCategoryView,
    DeleteCategoryView,
    UpdateCategoryView,
    CreateTodoView,
    DeleteTodoView,
    UpdateTodoView,
)

app_name = "todo"

urlpatterns = [
    # Todo
    path('<int:pk>/', HomePage.as_view(), name="todo-home"),
    path('<int:pk1>/<int:pk2>/delete/', DeleteTodoView.as_view(), name="todo-delete"),
    path('<int:pk1>/<int:pk2>/update/', UpdateTodoView.as_view(), name="todo-update"),
    path('<int:pk>/create/', CreateTodoView.as_view(), name="todo-create"),
    # Category
    path('create/',CrateCategoryView.as_view(), name='category-create'),  
    path('<int:pk>/delete/',DeleteCategoryView.as_view(), name='category-delete'), 
    path('<int:pk>/update/',UpdateCategoryView.as_view(), name='category-update'), 
    path('', LandingPage.as_view(), name="landing"),
]

todoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls', namespace = 'todo')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

todo/models.py
from django.db import models
from django.db.models.fields import BooleanField, CharField

class Category(models.Model):
    category = models.CharField(max_length=20, default=None)
    description = models.CharField(max_length=100, default=None)
    date_begin = models.DateField()
    check = models.BooleanField(default=False)


    def __str__(self):
        return self.category
    
    class Meta:
        ordering = ['date_begin']

# Create your models here.
class Todo(models.Model):
    name = models.CharField(max_length=100, default=None)
    description = models.CharField(max_length=300, default=None)
    date_begin = models.DateField()
    date_end = models.DateField()
    check = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from django.db.models import fields
from .models import Category, Todo

class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            "category",
            "description",
            "date_begin",
            "check"
        )

class TodoModelForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = (
            "name",
            "description",
            "date_begin",
            "date_end",
            "check",
            "category",
        )

todo/views.py
from typing import Callable
from django.db.models import query
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render, reverse
from django.views import generic, View

from .forms import CategoryModelForm, TodoModelForm

from .models import (
    Todo,
    Category
)

########################
######## TODO ##########

class HomePage(generic.ListView):
    template_name = 'todo/todo_home.html'
    context_object_name = "todolists"
    # queryset = Todo.objects.all()

    def get_queryset(self):
        # Get the special astribute
        pk = self.kwargs.get('pk')
        category = Category.objects.filter(id=pk)[0]

        queryset = Todo.objects.filter(category__category=category)
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['pk'] = int(pk)
        return context

# Todo Create
class CreateTodoView(generic.CreateView):
    template_name = 'todo/todo_create.html'
    form_class = TodoModelForm

    def get_initial(self):
        pk = self.request.path.split("/")[1]
        print(pk)
        category = Category.objects.filter(id=pk)[0]
        return {'category':category}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['pk'] = int(pk)
        return context


    def get_success_url(self):
        pk = self.kwargs.get('pk')     
        return reverse('todo:todo-home', kwargs={'pk': pk})

# Todo Update
class UpdateTodoView(generic.UpdateView):
    template_name = 'todo/todo_update.html'
    form_class = TodoModelForm
    context_object_name = "context"
    
    def get_object(self):
        pk = self.kwargs.get('pk2')
        # Get the instance of queryset
        obj = Todo.objects.filter(id=pk).first()
        return obj
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk1 = self.kwargs.get('pk1')
        pk2 = self.kwargs.get('pk2')
        context['pk1'] = int(pk1)
        context['pk2'] = int(pk2)
        return context

    def get_success_url(self):
        pk = self.kwargs.get('pk1') 
        return reverse('todo:todo-home', kwargs={'pk': pk})
# Todo Delete
class DeleteTodoView(generic.DeleteView):
    template_name = 'todo/todo_delete.html'
    model = Todo
    context_object_name = "context"

    def get_object(self):
        pk = self.kwargs.get('pk2')
        queryset = Todo.objects.filter(id=pk)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk1 = self.kwargs.get('pk1')
        pk2 = self.kwargs.get('pk2')
        context['pk1'] = int(pk1)
        context['pk2'] = int(pk2)
        return context

    def get_success_url(self):
        pk = self.kwargs.get('pk1') 
        return reverse('todo:todo-home', kwargs={'pk': pk})

##########################
####### Category #########
    
class LandingPage(generic.ListView):
    template_name = 'todo/todo_landing.html'
    context_object_name = "categories"

    def get_queryset(self):
        queryset = Category.objects.all()
        return queryset

# Create A category
class CrateCategoryView(generic.CreateView):
    template_name = 'todo/category_create.html'
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse('todo:landing')

# Update A Category
class UpdateCategoryView(generic.UpdateView):
    template_name = 'todo/category_update.html'
    form_class = CategoryModelForm

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        obj = Category.objects.filter(id=pk)
        return obj

    def get_success_url(self):
        return reverse('todo:landing')

# Delete A Category
class DeleteCategoryView(generic.DeleteView):
    template_name = 'todo/category_delete.html'
    model = Category
    def get_success_url(self):
        return reverse('todo:landing')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <header class="text-gray-600 body-font">
        <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
          <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
              <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
            </svg>
            <span class="ml-3 text-xl">HiuAndRot</span>
          </a>
          <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            <a href="{% url 'todo:landing' %}" class="mr-5 hover:text-gray-900">Categories</a>
            <a href="{% url 'todo:category-create' %}" class="mr-5 hover:text-gray-900">Create</a>
          </nav>
          {% if request.user.is_authenticated %}
            Logged in as: {{ request.user.username }}
            <a href="{% url 'logout' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0 ml-3">
              Logout
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          {% else %}
            <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
              Login
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          {% endif %}
        </div>
    </header>
    
</head>
<body>
    {% block content %}
    {% endblock content %}
    {% block jquery %}
    {% endblock jquery %}
</body>
</html>

todo/templates/todo/category_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="flex justify-center mb-5">
            <div class="text-center"> <!-- ⬅️ THIS DIV WILL BE CENTERED -->
                <h1 class="text-3xl">Create a new Category</h1>
            </div>
          </div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
        </form>

        <div class="py-5 border-t border-gray-200 mt-5">
            <a class="hover:text-blue-500 mt-3" href="{% url 'todo:landing' %}">Go back to Category</a>
        </div>

    </div>
{% endblock content %}

todo/templates/todo/category_delete.html
{% extends "base.html" %}
{% block content %}

    <div class="max-w-lg mx-auto">
        <div class="flex justify-center mb-5">
            <div class="text-center"> <!-- ⬅️ THIS DIV WILL BE CENTERED -->
                <h1 class="text-3xl">Delete this Category?</h1>
            </div>
        </div>
        <form action="" method="post">
            {% csrf_token %}

            <button type="submit" class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md">Submit</button>
        </form>

        <div class="py-5 border-t border-gray-200 mt-5">
            <a class="hover:text-blue-500 mt-3" href="{% url 'todo:landing' %}">Go back to Category</a>
        </div>

    </div>
{% endblock content %}

todo/templates/todo/category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="flex justify-center mb-5">
            <div class="text-center"> <!-- ⬅️ THIS DIV WILL BE CENTERED -->
                <h1 class="text-3xl">Update this category</h1>
            </div>
          </div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
        </form>

        <div class="py-5 border-t border-gray-200 mt-5">
            <a class="hover:text-blue-500 mt-3" href="{% url 'todo:landing' %}">Go back to Category</a>
        </div>

    </div>

{% endblock content %}

todo/templates/todo/todo_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}
    <div class="max-w-lg mx-auto">
        
        <div class="flex justify-center mb-5">
            <div class="text-center"> <!-- ⬅️ THIS DIV WILL BE CENTERED -->
                <h1 class="text-3xl">Create a new task</h1>
            </div>
          </div>

        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
        </form>

        <div class="py-5 border-t border-gray-200 mt-5">
            <a class="hover:text-blue-500 mt-3" href="{% url 'todo:todo-home' pk %}">Go back to Todo</a>
        </div>

    </div>

{% endblock content %}    

todo/templates/todo/todo_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="max-w-lg mx-auto">
        <div class="flex justify-center mb-5">
            <div class="text-center"> <!-- ⬅️ THIS DIV WILL BE CENTERED -->
                <h1 class="text-3xl">Delete this lead?</h1>
            </div>
          </div>
        <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="w-full text-white bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md">Submit</button>
        </form>

        <div class="py-5 border-t border-gray-200 mt-5">
            <a class="hover:text-blue-500 mt-3" href="{% url 'todo:todo-home' pk1 %}">Go back to Todo</a>
        </div>

    </div>

{% endblock content %}

todo/templates/todo/todo_home.html
{% extends 'base.html' %}

{% block content %}
    <section class="text-gray-600 body-font">
        <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ todolists.0.category }}</h1>
        </div>
       
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Task</th>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Description</th>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Begin</th>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">DeadLine</th>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100"></th>
                    <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br">Action</th>
                    </tr>
                </thead>
                {% for todo in todolists %}
                    <tbody>
                        <tr>
                        <td class="px-4 py-3">{{ todo.name }}</td>
                        <td class="px-4 py-3">{{ todo.description }}</td>
                        <td class="px-4 py-3">{{ todo.date_begin }}</td>
                        <td class="px-4 py-3 text-lg text-gray-900">{{ todo.date_end }}</td>
                        <td class="w-10 text-center">
                            <a href="{% url 'todo:todo-update' pk todo.pk %}" class="link-delete text-green-600">Update</a>
                        </td>
                        <td class="w-10 text-center">
                            <a href="{% url 'todo:todo-delete' pk todo.pk %}" class="link-delete text-red-600">Delete</a>
                        </td>
                        </tr>
                    </tbody>
                {% endfor %}
            </table>
        </div>

        <div class="flex justify-center mt-5 mx-auto">
            <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0" href="{% url 'todo:todo-create' pk %}">
                <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Create New One
                </button>
            </a>
        </div>

    </section>
    

{% endblock content %}

{% block script %}
<script>
    $(".link-delete").on("click", function(e){
        e.preventDefault();
        var $this = $(this);
        if(confirm("Sure to delete?")){
            $.ajax({
                url: this.attr("href"),
                type: "GET",
                dataType: "jsson",
                success: function (resp){
                    if(resp.message === 'success'){
                        $this.parents('.record').fadeOut("slow", function(){
                            $this.parents('.record').remove();
                        })
                    }
                    else{
                        alert(resp.message)
                    }
                },
                error: function (resp){
                    console.log("Something went wrong");
                }
            })
        }
        return false;
    });
</script>
{% endblock %}

todo/templates/todo/todo_landing.html
{% extends "base.html" %}

{% block content %}
    {% for category in categories %}
            <section class="text-gray-600 body-font overflow-hidden">
                <div class="container px-5 py-24 mx-auto">
                    <div class="-my-8 divide-y-2 divide-gray-100">
                        <div class="py-8 flex flex-wrap md:flex-nowrap">
                            <div class="md:w-64 md:mb-0 mb-6 flex-shrink-0 flex flex-col">
                                <span class="font-semibold title-font text-gray-700">{{ category.category }}</span>
                                <span class="mt-1 text-gray-500 text-sm">{{ category.begin_date }}</span>
                            </div>
                            <div class="md:flex-grow">
                                <h2 class="text-2xl font-medium text-gray-900 title-font mb-2">{{ category.description }}</h2>
                                <a href="{% url 'todo:todo-home' category.pk %}" class="text-indigo-500 inline-flex items-center mt-4">
                                    View More
                                </a>
                                <a href="{% url 'todo:category-create'%}" class="ml-3 text-green-600">Create</a>
                                <a href="{% url 'todo:category-delete' category.pk %}" class="ml-3 text-red-600">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

    {% endfor %}

{% endblock content %}

todo/templates/todo/todo_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
    <div class="max-w-lg mx-auto">
        <h1> Update a Todo </h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
        </form>

        <div class="py-5 border-t border-gray-200 mt-5">
            <a class="hover:text-blue-500 mt-3" href="{% url 'todo:todo-home' pk1 %}">Go back to Todo List</a>
        </div>

    </div>
{% endblock content %}